### PR TITLE
Update release.yml

### PR DESCRIPTION
**Pull request by ivy-lmu**

### CODE REVIEW

**Review by ivy-rew — APPROVED** [review]
smart

**Comment by alexsuter** [comment]
Why we need that here and in other repos not?

**Comment by ivy-rew** [comment]
In other repos we have that information duplicated into each of the 3 connector related POMs.
Unfortunately without having any advice in the docs: with this property, it comes with a good default and most customers should not need to think about it.

**Comment by alexsuter** [comment]
Ok for me. But the test project should not be deployed - so only 2 pom.xml should be affected.

**Review by alexsuter — APPROVED** [review]

**Pull request merged**
